name: Vavoo M3U Guncelleyici

on:
  schedule:
    - cron: '0 */12 * * *' # 12 saatte bir çalışır
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Depoyu kopyala
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Yukle
      run: pip install requests

    - name: M3U Listesini Olustur
      run: python main.py --full-m3u

    - name: Degisiklikleri Kaydet ve Yukle
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add vavoo_full.m3u
        git commit -m "Güncel Vavoo M3U Listesi" || exit 0
        git push
